### ISSUE TITLE
Compilation to WebAssembly 

### ISSUE THREAD

**Issue by AMagd** [rordenlab/niimath#23]
Could you provide details (steps) to how to compile niimath to WebAssembly on Windows?

**Comment by neurolabusc** [comment]
See [JavaScript.md](https://github.com/rordenlab/niimath/blob/86aa166cc23f7c33ce2b407098a2474187997d3d/src/JavaScript.md). The current build directly passes linear memory to and from niimath. Perhaps a better approach would be to use a virtual file system. Feel free to make a pull request with a more flexible implementation. You may want to look at work from @wpmed92:

 - [niivue-dcm2niix](https://github.com/softwiredtech/niivue-dcm2niix)
 - [niivue-bet](https://github.com/softwiredtech/niivue-bet)
 - [niivue-flirt](https://github.com/softwiredtech/niivue-flirt)

**Comment by wpmed92** [comment]
@AMagd My ports produce the command line equivalents in webassembly, so they are not compiled as libs. Feel free to reach out to help with the compilation.
