### ISSUE TITLE
Niimath report header unnecessarily loads the whole data to memory

### ISSUE THREAD

**Issue by suxpert** [rordenlab/niimath#24]
`niimath` can be used as replacement of `fslhd` via calling with only 1 arguments:
https://github.com/rordenlab/niimath/blob/86aa166cc23f7c33ce2b407098a2474187997d3d/src/niimath.c#L232

But from the code we can see that it load the whole data to memory, which is unnecessary because we only need the *header*, which is only few bits. If I use `niimath` to get the header information, it spends much longer than `fslhd` when the NifTi file is large, which is very common for high resolution functional scans.

**Comment by neurolabusc** [comment]
@suxpert this is a nice suggestion. The latest commit only loads the header data. The result is faster and makes less memory demands. You can see this with running a command like `/usr/bin/time -l niimath dti.nii` where the NIfTI image is a larger image (in this case 23mb). 

Before commit:
```
0.23 real         0.00 user         0.00 sys
...
23856064  peak memory footprint
```
after commit:
```
0.00 real         0.00 user         0.00 sys
1016704  peak memory footprint
```
