### ISSUE TITLE
Support for statically linked binaries on Linux.

### ISSUE THREAD

**Issue by Vbitz** [rordenlab/niimath#30]
I was able to compile a static binary on Linux using the command `gcc -O3 -static -std=gnu99 -DHAVE_BUTTERWORTH bw.c -DHAVE_TENSOR tensor.c -DHAVE_FORMATS base64.c -DNII2MESH meshify.c quadric.c bwlabel.c radixsort.c fdr.c -DUSE_CLASSIC_CUBES oldcubes.c niimath.c core.c core32.c niftilib/nifti2_io.c znzlib/znzlib.c -I./niftilib -I./znzlib -DFSLSTYLE -DPIGZ -DREJECT_COMPLEX -lm conform.c -DHAVE_CONFORM -DHAVE_64BITS core64.c -DHAVE_ZLIB -lz -flto -o niimath` in the `src` directory.

I did it on Alpine Linux 3.20 using `build-base`, `zlib-dev`, and `zlib-static`.

The current release links to Glibc so it won't run on docker containers using Musl.

**Comment by neurolabusc** [comment]
@Vbitz can you test the latest commit. This provides the option to build niimath with static linking. Note that Windows and [MacOS](https://crystal-lang.org/reference/1.13/guides/static_linking.html#macos) do not support static linking. Do you think we should add an option to allow static linking for [dcm2niix](https://github.com/rordenlab/dcm2niix)?

```
git clone https://github.com/rordenlab/niimath.git
cd niimath/src
make static
```

**Comment by Vbitz** [comment]
That's awesome. Thanks for the fast response.

I was building `niimath` container for NeuroDesk (https://github.com/NeuroDesk/neurocontainers/pull/793) and wanted to use a multi-stage build to reduce the final container size. That option means I don't have to hardcode the compile command anymore (https://github.com/NeuroDesk/neurocontainers/pull/793/files#diff-d0f37ef78602c4b2cbe2c5972c33508966e1c4f1b1c57bc6c0c279281e753bdcR19).

I think it might be nice for `dcm2niix` if it's not too much work. Might make adding the tools as dependencies to other pipelines easier.
