### ISSUE TITLE
run otsu masking prior to dog edge detect?

### ISSUE THREAD

**Issue by hanayik** [rordenlab/niimath#7]
One thing I noticed in the dog edge results in my testing was that there are a lot of "edges" (zero crossings) in the background of the input image. This is the same for T1w, EPI, etc (although less background in smaller FOV images). Would it be unreasonable to first mask the foreground from the background using niimath's otsu method, and then mask the dog edge output with the otsu mask? It would make the edge result images look cleaner. I have tested this some and it works ok. But the test image set (from the DoG repo) is quite limited.

**Comment by neurolabusc** [comment]
I had thought about this as well. MRIcroGL includes the "Remove Haze" function in the "View" menu, as well as "Remove haze with options". These are [described here](https://github.com/rordenlab/MRIcroGL/tree/master/Haze). I can add these to niimath, so they will be available to NiiVue via WASM. However, I note that the AFNI folks espouse the "warts and all" view of display, and one could argue that sometimes the haze may show meaningful artifacts (motion, Gibbs, etc).

**Comment by neurolabusc** [comment]
Note that nii_math already has a binary `otsu` function, which will make a binary mask. However, this is not ideal for most MRI scans, where multiple tissue types that give different signal, e.g. for T1 air (darkest), water, gray matter/muscle, white matter (brightest). This explains why the default MRIcroGL behavior is to estimate a [4 level Otsu](https://scikit-image.org/docs/dev/auto_examples/segmentation/plot_multiotsu.html) and only zero the darkest class.

**Comment by neurolabusc** [comment]
@hanayik can you try out the latest commit to see what you think. There is a new function `-dehaze`. The `-otsu` command generates a binary image (every voxel 0 or 1), the `-dehaze` command zeros voxels below the threshold (the dehaze is also dilated one voxel to capture partial volume effects). The parameter 1..5 sets the threshold level, with larger value letting more bright voxels survive the threshold. For most cases, I would choose `5` which computes a 4 tissue Otsu (e.g. for T1 this would be air, CSF, GM/muscle, WM/fat) and only makes the zeros the darkest tissue (allowing 3 of the 4 tissues to survive):

 1. 1/4
 2. 1/3
 3. 1/2
 4. 2/3
 5. 3/4

```
git clone https://github.com/rordenlab/niimath/  
cd niimath/src
make -j
./niimath ~/Desktop/T1 -dehaze 5 -dog 2 3.2 dog2
```

At the moment, voxels that do not survive dehaze are set to zero. This is appropriate for MRI magnitude images and statistical maps. However, for CT scans the air is -1000 and bone is +1000. An alternative might be for dehaze to set voxels that do not survive to the darkest intensity of the voxel in the volume. What do you think?

**Comment by hanayik** [comment]
Will try it out. For CT, what about implementing the h2c function from the clinical toolbox Matlab code?
________________________________

**Comment by neurolabusc** [comment]
@hanayik  

1. I have implemented the h2c (Hounsfield to Cormack) transform (which emphasizes contrast on soft tissue, and makes all CT values positive) and the c2h reverse transform. 
2. Alternatively, I have added the option to specify a negative value for the `-dehaze` function. A negative value works identically the absolute value, except masked voxels are filled with the global minimum intensity rather than zero.

You can test this with these [Sample CT images](https://github.com/neurolabusc/dcm_qa_ct).

```
niimath ct -h2c -dehaze 5 -c2h cth2
niimath ct -dehaze -5 ctm2 
```

**Comment by hanayik** [comment]
Thanks! h2c works nicely.

From: Chris Rorden ***@***.***>
Date: Sunday, 28 November 2021 at 5:46 pm
To: rordenlab/niimath ***@***.***>
Cc: Taylor Hanayik ***@***.***>, Mention ***@***.***>
Subject: Re: [rordenlab/niimath] run otsu masking prior to dog edge detect? (Issue #7)

@hanayik<https://github.com/hanayik>

  1.  I have implemented the h2c (Hounsfield to Cormack) transform (which emphasizes contrast on soft tissue, and makes all CT values positive) and the c2h reverse transform.
  2.  Alternatively, I have added the option to specify a negative value for the -dehaze function. A negative value works identically the absolute value, except masked voxels are filled with the global minimum intensity rather than zero.

You can test this with these Sample CT images<https://github.com/neurolabusc/dcm_qa_ct>.

niimath ct -h2c -dehaze 5 -c2h cth2

niimath ct -dehaze -5 ctm2
